apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  serviceAccountName: alertmanager-main
  baseImage: quay.io/prometheus/alertmanager
  externalUrl: http://127.0.0.1:9093
  replicas: 3
  version: v0.15.0
