apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: external-dns
data:
  Corefile: |-
    .:53 {
      log . {
        class denial
      }
      cache
      errors
      loadbalance round_robin
      whoami
      health
      prometheus 0.0.0.0:9153
      proxy . 8.8.8.8:53
    }

    k8s.local {
      etcd k8s.local {
        stubzones
        path /skydns
        endpoint http://coredns-etcd:2379
        upstream 8.8.8.8:53 8.8.4.4:53
        debug
      }
      errors
      log
    }
